title: Tim Krehan
description: >
  This is my personal site

author:
  name: Tim Krehan

theme: minima
minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto
  
  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - about.md

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  date_format: "%d.%m.%Y"

  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
  social_links:
    - title: Me at GitHub
      icon: github
      url: "https://github.com/tim-krehan"
    - title: Freiwillige Feuerwehr Großgründlach
      icon: fire-extinguisher
      url: "https://ff-grossgruendlach.de"
    - title: Xing
      icon: xing
      url: https://www.xing.com/profile/Tim_Krehan
    - title: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/tim-krehan-b6b24a209/
